$ErrorActionPreference="Stop"
$base="https://www.feijoadadomaster.com.br"
$ses=$null
Invoke-WebRequest "$base/admin/login" -Method POST -Body @{senha=$env:FM_SENHA} -UseBasicParsing -SessionVariable ses -MaximumRedirection 0 -ErrorAction SilentlyContinue | Out-Null
function Salvar($corpo){ $r = Invoke-WebRequest "$base/admin/conteudo/salvar" -Method POST -Body $corpo -UseBasicParsing -WebSession $ses; if($r.Content -match "N(a|ã)o deu"){ "FALHOU: " + $corpo["ent"] } }

# fonte
Salvar @{ ent='fonte'; id='jdb'; rotulo='Jornal de Brasília — mensagens sobre Mendonça e filhos de Fux e Kassio'; url='https://jornaldebrasilia.com.br/noticias/politica-e-poder/veja-o-que-dizem-mensagens-no-celular-de-vorcaro-sobre-andre-mendonca-e-filhos-de-fux-e-kassio/'; motivo='nova fonte: reportagem do Jornal de Brasilia de 15/09/2026' }

# verbetes
Salvar @{ ent='verbete'; id='fux'; nome='Luiz Fux'; sigla='LF'; papel='Ministro do STF'; categoria='jud'; anel='2'; info='A reportagem de 15/09/2026 não o aponta como investigado: seu nome entra no caso por mensagens que envolvem o filho, Rodrigo Fux. Não se manifestou na matéria.'; fontes='jdb'; wiki='Luiz Fux'; ordem='200'; motivo='inclusao a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='verbete'; id='rodrigofux'; nome='Rodrigo Fux'; sigla='RF'; papel='Advogado, filho do ministro Fux'; categoria='pol'; anel='4'; info='Segundo mensagens divulgadas em 15/09/2026, tratava Vorcaro como "irmão" em mai/2024 e, em mar/2025, pediu que informações sobre um compromisso em Londres fossem enviadas à secretária do pai no STF. Não se manifestou.'; fontes='jdb'; wiki=''; ordem='201'; motivo='inclusao a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='verbete'; id='kevin'; nome='Kevin Marques'; sigla='KM'; papel='Filho do ministro Kassio Nunes Marques'; categoria='pol'; anel='4'; info='Anotação atribuída a Luiz Rennó, de out/2024, menciona pagamentos mensais de R$ 500 mil a ele e usa a expressão "Dominado aqui" após voto favorável do ministro em caso de destilaria; a referência reaparece em jul/2025. Não se manifestou.'; fontes='jdb'; wiki=''; ordem='202'; motivo='inclusao a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='verbete'; id='renno'; nome='Luiz Rennó'; sigla='LR'; papel='Interlocutor de Vorcaro nas mensagens'; categoria='mkt'; anel='4'; info='Autor, segundo a reportagem, das anotações sobre pagamentos ligados ao filho de Kassio Nunes Marques. Não se manifestou.'; fontes='jdb'; wiki=''; ordem='203'; motivo='inclusao a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='verbete'; id='ciroadv'; nome='Ciro Soares'; sigla='CS'; papel='Advogado'; categoria='pol'; anel='4'; info='Em 08/02/2025 mostrou a Vorcaro uma foto ao lado do ministro André Mendonça e, em 16/02, escreveu que "o A.M. quer recebê-lo", pedindo para agendar. Não se manifestou.'; fontes='jdb'; wiki=''; ordem='204'; motivo='inclusao a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='verbete'; id='marcusv'; nome='Marcus Vinicius'; sigla='MV'; papel='Advogado'; categoria='pol'; anel='4'; info='Em abr/2024 relatou a Vorcaro reunião com Mendonça no STF e combinou encontrá-lo em seguida; no dia seguinte tratou de novo horário. Em jul/2024 respondeu sobre um processo no Supremo que "tudo tem como o amigo". Não se manifestou.'; fontes='jdb'; wiki=''; ordem='205'; motivo='inclusao a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='verbete'; id='cezinha'; nome='Cezinha de Madureira'; sigla='CM'; papel='Deputado federal (PL-SP)'; categoria='pol'; anel='3'; info='Alvo de fase da Operação Compliance Zero. Segundo as mensagens, avisou Vorcaro em 13/03/2025 sobre encontro "com ministro André em São Paulo" e, no dia seguinte, escreveu que o "ministro já está te esperando". Não se manifestou.'; fontes='jdb'; wiki=''; ordem='206'; motivo='inclusao a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='verbete'; id='iter'; nome='Instituto Iter'; sigla='IT'; papel='Instituto fundado por André Mendonça'; categoria='pol'; anel='4'; info='Vorcaro foi convidado ao menos duas vezes a eventos do instituto, entre eles um debate no hotel Fasano de Belo Horizonte com o próprio ministro, para "poucos convidados". A reportagem não confirma se ele compareceu.'; fontes='jdb'; wiki=''; ordem='207'; motivo='inclusao a partir da reportagem do Jornal de Brasilia de 15/09/2026' }

# vinculos
Salvar @{ ent='vinculo'; origem='vorcaro'; destino='rodrigofux'; tipo='p'; info='Mensagens de mai/2024 mostram tratamento próximo ("irmão"); em mar/2025, pedido para enviar informação à secretária do ministro Fux no STF.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='rodrigofux'; destino='fux'; tipo='p'; info='Pai e filho. O ministro não é apontado como investigado na reportagem.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='vorcaro'; destino='kevin'; tipo='p'; info='Anotação de out/2024 atribuída a Luiz Rennó menciona R$ 500 mil mensais ao filho do ministro Kassio.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='kevin'; destino='kassio'; tipo='p'; info='Pai e filho. O ministro não se manifestou sobre as mensagens.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='renno'; destino='kevin'; tipo='p'; info='Rennó é apontado como autor da anotação sobre os pagamentos mensais.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='vorcaro'; destino='renno'; tipo='p'; info='Interlocutor direto do banqueiro nas conversas divulgadas.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='vorcaro'; destino='ciroadv'; tipo='p'; info='Advogado que se apresentou como ponte para o ministro Mendonça em fev/2025.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='ciroadv'; destino='mendonca'; tipo='p'; info='Mensagens citam foto ao lado do ministro e tentativa de agendar encontro. Mendonça não se manifestou na reportagem.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='vorcaro'; destino='marcusv'; tipo='p'; info='Advogado que relatou reuniões no STF e tratou de andamento processual com o banqueiro em 2024.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='marcusv'; destino='mendonca'; tipo='p'; info='Segundo as mensagens, dizia ter sido chamado pelo ministro no STF e combinava encontros com Vorcaro em seguida.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='vorcaro'; destino='cezinha'; tipo='p'; info='Deputado avisou sobre encontro com o ministro em São Paulo em mar/2025, segundo as mensagens.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='cezinha'; destino='mendonca'; tipo='p'; info='As mensagens do deputado tratam de encontro com "ministro André"; o ministro não se manifestou.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='vorcaro'; destino='iter'; tipo='p'; info='Convites a eventos do instituto, incluindo debate fechado em Belo Horizonte.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
Salvar @{ ent='vinculo'; origem='iter'; destino='mendonca'; tipo='p'; info='Instituto fundado pelo ministro, usado como contexto dos convites ao banqueiro.'; fontes='jdb'; ordem='200'; motivo='vinculo a partir da reportagem do Jornal de Brasilia de 15/09/2026' }

# evento na linha do tempo
Salvar @{ fase='4'; ordem='60'; data_txt='15/09/2026'; categoria='jud'; quem='Imprensa'; texto='Reportagem detalha mensagens do celular de Vorcaro sobre <b>André Mendonça</b> — via advogados e um deputado — e sobre os filhos de <b>Luiz Fux</b> e de <b>Kassio Nunes Marques</b>. Nenhum dos citados se manifestou na matéria.'; ent='evento'; motivo='evento a partir da reportagem do Jornal de Brasilia de 15/09/2026' }
"inseridos: 1 fonte, 8 verbetes, 14 vinculos, 1 evento"

